//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string ProductGroup { get; set; }
        public Nullable<int> ProductQuantity { get; set; }
        public Nullable<decimal> ProductPrice { get; set; }
        public string ProductFamily { get; set; }
        public string ProductType { get; set; }
    }
}
