//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medal
    {
        public int MedalID { get; set; }
        public string MedalName { get; set; }
        public string MedalGroup { get; set; }
        public Nullable<int> MedalQuantity { get; set; }
        public Nullable<double> MedalPrice { get; set; }
        public string MedalType { get; set; }
        public string MedalSize { get; set; }
        public string MedalFamily { get; set; }
    }
}
