//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trophy
    {
        public int TrophyPartID { get; set; }
        public string TrophyPartName { get; set; }
        public string TrophyPartGroup { get; set; }
        public Nullable<int> TrophyPartQuantity { get; set; }
        public Nullable<double> TrophyPartPrice { get; set; }
        public string TrophyPartSize { get; set; }
        public string TrophyPartType { get; set; }
    }
}
